"""Send emails with summaries and recruiter responses"""

import os
import smtplib
from datetime import datetime
from typing import List, Dict, Any
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from dotenv import load_dotenv

load_dotenv()

class EmailSender:
    """Handle sending emails via SMTP"""
    
    def __init__(self):
        """Initialize email sender with SMTP configuration"""
        self.sender_email = os.getenv('SENDER_EMAIL')
        self.sender_password = os.getenv('SENDER_PASSWORD')
        self.smtp_server = os.getenv('SMTP_SERVER', 'smtp.gmail.com')
        self.smtp_port = int(os.getenv('SMTP_PORT', '587'))
        
        if not self.sender_email or not self.sender_password:
            raise ValueError("SENDER_EMAIL and SENDER_PASSWORD must be set in .env file")
    
    def send_daily_summary(self, task_summaries: List[Dict], 
                          other_summaries: List[Dict], recipient: str):
        """
        Send daily summary email with task emails and other emails
        
        Args:
            task_summaries: List of task email summaries
            other_summaries: List of other email summaries (sender name + subject)
            recipient: Email address to send to
        """
        try:
            msg = MIMEMultipart()
            msg['From'] = self.sender_email
            msg['To'] = recipient
            msg['Subject'] = f"📧 Daily Email Summary - {datetime.now().strftime('%Y-%m-%d')}"
            
            # Create email body
            body = self._create_summary_body(task_summaries, other_summaries)
            
            msg.attach(MIMEText(body, 'plain', 'utf-8'))
            
            # Send email
            server = smtplib.SMTP(self.smtp_server, self.smtp_port)
            server.starttls()
            server.login(self.sender_email, self.sender_password)
            server.sendmail(self.sender_email, recipient, msg.as_string())
            server.quit()
            
            print(f"✅ Daily summary email sent to {recipient}")
            
        except Exception as e:
            print(f"❌ Error sending daily summary: {e}")
    
    def _create_summary_body(self, task_summaries: List[Dict], 
                            other_summaries: List[Dict]) -> str:
        """Create the body content for daily summary email"""
        body = f"""
📧 Daily Email Summary - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
{'='*80}

📊 SUMMARY STATISTICS:
• Task emails requiring action: {len(task_summaries)}
• Other emails: {len(other_summaries)}
• Total emails processed: {len(task_summaries) + len(other_summaries)}

"""
        
        # Task emails section
        if task_summaries:
            body += "📋 TASK EMAILS (Requiring Action):\n"
            body += "-" * 80 + "\n\n"
            for i, task in enumerate(task_summaries, 1):
                email = task['email']
                summary = task['summary']
                body += f"{i}. From: {email.get('sender_name', 'Unknown')} <{email.get('sender_email', '')}>\n"
                body += f"   Subject: {email.get('subject', 'No Subject')}\n"
                body += f"   Summary: {summary}\n\n"
        
        # Other emails section
        if other_summaries:
            body += "\n📬 OTHER EMAILS:\n"
            body += "-" * 80 + "\n\n"
            for i, other in enumerate(other_summaries, 1):
                body += f"{i}. {other.get('sender_name', 'Unknown')} - {other.get('subject', 'No Subject')}\n"
        
        body += f"\n{'='*80}\n"
        body += "This is an automated summary generated by the Recruiter Email Automation System.\n"
        
        return body
    
    def send_recruiter_response(self, email: Dict[str, Any], response: str, 
                               resume_path: str, recipient: str):
        """
        Send recruiter response email with generated response and resume
        
        Args:
            email: Original recruiter email
            response: Generated response text
            resume_path: Path to generated resume file
            recipient: Email address to send to
        """
        try:
            msg = MIMEMultipart()
            msg['From'] = self.sender_email
            msg['To'] = recipient
            msg['Subject'] = f"📧 Recruiter Response: {email.get('subject', 'No Subject')}"
            
            # Create email body
            body = f"""
📧 RECRUITER EMAIL RESPONSE
{'='*80}

ORIGINAL EMAIL:
From: {email.get('sender_name', 'Unknown')} <{email.get('sender_email', '')}>
Subject: {email.get('subject', 'No Subject')}
Date: {email.get('date_received', 'Unknown')}

{'='*80}

GENERATED RESPONSE:
{response}

{'='*80}

📎 ATTACHMENTS:
• Customized Resume: {os.path.basename(resume_path) if resume_path else 'Not generated'}

{'='*80}

⚠️  ACTION REQUIRED:
Please review the generated response above. You can:
1. Copy the response text
2. Attach the resume from: {resume_path}
3. Send the email to: {email.get('sender_email', '')}

This is an automated response generated by the Recruiter Email Automation System.
"""
            
            msg.attach(MIMEText(body, 'plain', 'utf-8'))
            
            # Attach resume if it exists
            if resume_path and os.path.exists(resume_path):
                try:
                    with open(resume_path, "rb") as attachment:
                        part = MIMEBase('application', 'octet-stream')
                        part.set_payload(attachment.read())
                    
                    encoders.encode_base64(part)
                    part.add_header(
                        'Content-Disposition',
                        f'attachment; filename= {os.path.basename(resume_path)}'
                    )
                    msg.attach(part)
                except Exception as e:
                    print(f"Warning: Could not attach resume: {e}")
            
            # Send email
            server = smtplib.SMTP(self.smtp_server, self.smtp_port)
            server.starttls()
            server.login(self.sender_email, self.sender_password)
            server.sendmail(self.sender_email, recipient, msg.as_string())
            server.quit()
            
            print(f"✅ Recruiter response email sent to {recipient}")
            
        except Exception as e:
            print(f"❌ Error sending recruiter response: {e}")



